### ISSUE TITLE
broken link in the HTML version

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [hplgit/primer.html#1]
In http://hplgit.github.io/primer.html/doc/pub/formulas/._formulas-readable001.html#___sec4 there is a link pointing to http://hplgit.github.io/primer.html/doc/pub/accesspy under "How to access Python for doing scientific computing" . This link seems to be broken. could you please take a look?

**Comment by hplgit** [comment]
Thanks for pointing this out. The link should work now.
